### ISSUE TITLE
prove five claims from kas15 with ndio

### ISSUE THREAD

**Issue by j6k4m8** [jovo/IndStudyFall15#4]

**Comment by jovo** [comment]
5 _more_ claims,
last weeks 5 claims and list of all claims is still outstanding, right?

On Wed, Sep 16, 2015 at 4:52 PM, Jordan Matelsky notifications@github.com
wrote:

> —
> Reply to this email directly or view it on GitHub
> https://github.com/jovo/IndStudyFall15/issues/4.

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, calendar
https://www.google.com/calendar/embed?src=afr9t36kknt629jh4omun20n90%40group.calendar.google.com&ctz=America/New_York

**Comment by j6k4m8** [comment]
10 total + list of claims, yep!
